// const cardList = [
//   {
//     id: 1,
//     title: "Название задачи",
//     theme: "Web Design",
//     date: "30.10.23",
//     status: "Без статуса",
//   },
//   {
//     id: 2,
//     title: "Название задачи",
//     theme: "Research",
//     date: "30.10.23",
//     status: "Без статуса",
//   },
//   {
//     id: 3,
//     title: "Название задачи",
//     theme: "Web Design",
//     date: "30.10.23",
//     status: "Без статуса",
//   },
//   {
//     id: 4,
//     title: "Название задачи",
//     theme: "Copywriting",
//     date: "30.10.23",
//     status: "Без статуса",
//   },
//   {
//     id: 5,
//     title: "Название задачи",
//     theme: "Web Design",
//     date: "30.10.23",
//     status: "Без статуса",
//   },
//   {
//     id: 6,
//     title: "Название задачи",
//     theme: "Research",
//     date: "30.10.23",
//     status: "НУЖНО СДЕЛАТЬ",
//   },
//   {
//     id: 7,
//     title: "Название задачи",
//     theme: "Research",
//     date: "30.10.23",
//     status: "В РАБОТЕ",
//   },
//   {
//     id: 8,
//     title: "Название задачи",
//     theme: "Copywriting",
//     date: "30.10.23",
//     status: "В РАБОТЕ",
//   },
//   {
//     id: 9,
//     title: "Название задачи",
//     theme: "Web Design",
//     date: "30.10.23",
//     status: "В РАБОТЕ",
//   },
//   {
//     id: 10,
//     title: "Название задачи",
//     theme: "Research",
//     date: "30.10.23",
//     status: "ТЕСТИРОВАНИЕ",
//   },
//   {
//     id: 11,
//     title: "Название задачи",
//     theme: "Research",
//     date: "30.10.23",
//     status: "ГОТОВО",
//   },
// ];

// export default cardList;
